name: Golang

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58

  vuln:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.22.1
           go-package: ./...